### PR TITLE
taxcalc.js - fix issue with deprecatedPriceFieldsSupport config.

### PR DESCRIPTION
**Pull request by afirlejczyk**
- invoke updateProductPrices with correct values

### CODE REVIEW

**Comment by afirlejczyk** [comment]
I see new PR regarding taxes https://github.com/DivanteLtd/vue-storefront-api/pull/356/files
so we probably can close this one.

**Comment by andrzejewsky** [comment]
@afirlejczyk Could please change destination branch to the `release/v1.11-rc1` ?

**Comment by afirlejczyk** [comment]
@andrzejewsky sure, I will do it later today.

**Comment by afirlejczyk** [comment]
@andrzejewsky  done

**Pull request merged**
