### PR TITLE
Added basic typescript support

### PR DESCRIPTION
**Pull request by ResuBaka**
* Changed config package usage to config.get(\<path\>) which can lead to errors as when
the config value does not exist as it throws an error when that happens. But that
should not happen as these values are in the default.json.
* Change the dev command to use ts-node instead of babel-node
* Use tsc to build the source code instead of babel
* Added types for body-parser, config, express and node 

#210

### CODE REVIEW

**Comment by pkarw** [comment]
@ResuBaka please take care of the failing check + let me know when it's ready to test + merge to decelop

**Comment by ResuBaka** [comment]
@pkarw  I have fixed them now with merging upstream develop into my branch.

**Comment by pkarw** [comment]
OK thanks @lukeromanowicz will decide if to merge it to develop

**Comment by ResuBaka** [comment]
@lukeromanowicz  I added the  mount to the docker-compose file and added --build to tsc command.

**Pull request merged**
