### PR TITLE
Fixed elasticsearch url protocol

### PR DESCRIPTION
**Pull request by gopkumargopi**

### CODE REVIEW

**Comment by pkarw** [comment]
Thanks! Please do PRs to “develop”, we’re pushing just new releases and hotfixes to master

**Comment by hunterjamesio** [comment]
I appreciate this is merged but I don't believe it completely solves the issue?

There are other files that reference the protocol such as `src/graphql/elasticsearch/client.js`. Do they also need changing?

**Comment by pkarw** [comment]
You may be right @hunterjamesio - thanks for pointing this out. Could You please check it?

**Comment by hunterjamesio** [comment]
Another one seems to [`scripts/elastic.js`](https://github.com/DivanteLtd/vue-storefront-api/blob/3e4a6582b7a0dd122855ebf6fc7598fd75777b34/scripts/elastic.js#L17), will let you know if I come across others. Will give @gopkumargopi opportunity to fix his PR first :)

**Comment by hunterjamesio** [comment]
Also at [src/platform/magento2/tax.js](https://github.com/DivanteLtd/vue-storefront-api/blob/adb300cc307429258013a1df56547b9db3618152/src/platform/magento2/tax.js#L63)

I changed to:
```js
          host: {
            host: this._config.elasticsearch.host,
            port: this._config.elasticsearch.port,
            protocol: this._config.elasticsearch.protocol || 'http'
          },
```

**Comment by pkarw** [comment]
@hunterjamesio i think you don’t have to use the protocol settings key but setting url schema (https) into host will work exactly the same way

**Comment by hunterjamesio** [comment]
Correct! My bad.

**Pull request merged**
