### PR TITLE
Add make, python and g++ to dockerfile

### PR DESCRIPTION
**Pull request by ProxiBlue**
Please refer to: #448

(old PR: https://github.com/DivanteLtd/vue-storefront-api/pull/449)
swapped PR to develop

### CODE REVIEW

**Comment by ResuBaka** [comment]
Could you please add an changeglog entry, after that I would merge it.

**Comment by ProxiBlue** [comment]
> Could you please add an changeglog entry, after that I would merge it

Sure, at what version number? and that would require me to increase versions as well?

**Comment by ProxiBlue** [comment]
Next version would be 1.11.2, as a minor fix. Not 100% sure what files woudl hold the package version, if you can point me, I can go update.

**Comment by gibkigonzo** [comment]
@ProxiBlue add it to `1.12` in changelog :)

**Comment by ProxiBlue** [comment]
Changelog updated

**Comment by pkarw** [comment]
@gibkigonzo @ResuBaka has this one been ported to `storefront-api`?

**Comment by ResuBaka** [comment]
Yea `python`, `make` and `g++` is in the storefront-api [docker image](https://github.com/DivanteLtd/storefront-api/blame/master/docker/storefront-api/Dockerfile#L7).

**Pull request merged**
