### PR TITLE
Feature/# change password

### PR DESCRIPTION
**Pull request by Fifciu**
Added `create-password` password endpoint for user's controller. Now we can set a new password with token from the `reset-password`.

After reseting password, we are receiving a resetToken. Then we should send it to the POST `/api/user/create-password` like that:
```
{
  "resetToken": "myToken",
  "newPassword": "someSuperStrong123!@Password",
   "email": "myemail@gmail.com"
}
```

After that, a password will be updated if there are no errors.

About platform compatibility, I added `resetPasswordUsingResetToken` function only for `magento2` platform as I am only using this one.

## Multistore
If you are using multistore - request's URL should be equal: `/api/user/create-password?storeCode=<your_store_code>`

### CODE REVIEW

**Comment by andrzejewsky** [comment]
@pkarw I think `create-password` is fine because you basically create a new password based on the reset token and `reset-password` already exists.

**Comment by pkarw** [comment]
@Fifciu please resolve the conflicts + update the changelog

**Comment by Fifciu** [comment]
Done. I've merged master to my branch.

**Comment by andrzejewsky** [comment]
@Fifciu please resolve this one conflict and it's ready to merge.

**Pull request merged**
